cigdia = int(input("Quantos cigarros por dia"))
anofum = int(input("Quantos anos de fumante"))
tocig = (((cigdia * 365) * anofum)
arkcig = (((tocig * 10) /60) /24)
print(arkcig, "Dias de vida a menos")
